server:
  port: 8001

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
#饥饿加载，防止初次创建RibbonClient时间过长导致崩溃
ribbon:
  eager-load:
    enabled: true
    clients: api-admin, api-base, api-cms #配置相关服务